import { HandHelping, Utensils, BellRing, Sparkles, Eye, Smartphone, GlassWater, ShieldCheck, Download, Search, Youtube, Zap } from 'lucide-react';

export const LATEST_CHANGELOG_VERSION = '1.6.0';

export const changelog = [
    {
        version: '1.6.0',
        title: {
            en: 'Search & Speed Update!',
            ar: 'تحديث البحث والسرعة!',
        },
        features: [
            {
                icon: Search,
                title: {
                    en: 'Find Recipes by Name',
                    ar: 'ابحث عن الوصفات بالاسم',
                },
                description: {
                    en: 'Looking for a specific dish? Use the new "Search by Name" mode to find popular recipes like "KFC Chicken" or "Mahshi" instantly.',
                    ar: 'هل تبحث عن طبق معين؟ استخدم وضع "البحث بالاسم" الجديد للعثور فورًا على وصفات شهيرة مثل "دجاج كنتاكي" أو "المحشي".',
                },
            },
            {
                icon: Youtube,
                title: {
                    en: 'Better Video Tutorials',
                    ar: 'فيديوهات تعليمية أفضل',
                },
                description: {
                    en: 'We\'ve improved our AI to find the best and most popular YouTube tutorials for your recipes, making cooking even easier.',
                    ar: 'لقد قمنا بتحسين الذكاء الاصطناعي للعثور على أفضل فيديوهات اليوتيوب التعليمية وأكثرها شهرة لوصفاتك، مما يجعل الطهي أسهل.',
                },
            },
            {
                icon: Zap,
                title: {
                    en: 'Faster Recipe Generation',
                    ar: 'إنشاء وصفات أسرع',
                },
                description: {
                    en: 'Recipe images have been temporarily disabled to make generating your culinary creations significantly faster.',
                    ar: 'تم تعطيل صور الوصفات مؤقتًا لجعل عملية إنشاء إبداعاتك في الطهي أسرع بكثير.',
                },
            },
        ],
    },
    {
        version: '1.5.0',
        title: {
            en: 'Your Chef on Your Home Screen!',
            ar: 'الشيف على شاشتك الرئيسية!',
        },
        features: [
            {
                icon: Download,
                title: {
                    en: 'Install as an App',
                    ar: 'ثبّت التطبيق',
                },
                description: {
                    en: 'You can now add Chef in Your Pocket to your home screen for a faster, app-like experience! On Android/Chrome, tap "Install". On iOS/Safari, tap the Share button and then "Add to Home Screen".',
                    ar: 'يمكنك الآن إضافة "شيف في جيبك" إلى شاشتك الرئيسية لتجربة أسرع شبيهة بالتطبيقات! على أندرويد/كروم، انقر على "تثبيت". على آيفون/سفاري، انقر على زر المشاركة ثم "إضافة إلى الشاشة الرئيسية".',
                },
            },
        ],
    },
    {
        version: '1.4.0',
        title: {
            en: "Respecting Your Preferences",
            ar: "نحترم تفضيلاتك",
        },
        features: [
            {
                icon: ShieldCheck,
                title: {
                    en: 'Pork & Alcohol-Free Recipes',
                    ar: 'وصفات خالية من لحم الخنزير والكحول',
                },
                description: {
                    en: 'All recipes generated by our AI are now guaranteed to be free of pork and alcohol, respecting your dietary and cultural needs.',
                    ar: 'نضمن الآن أن جميع الوصفات التي يتم إنشاؤها خالية تمامًا من لحم الخنزير والكحول، احترامًا لاحتياجاتك الغذائية والثقافية.',
                },
            },
        ],
    },
    {
        version: '1.3.0',
        title: {
            en: "A Fresh & Animated Update!",
            ar: "تحديث جديد وحيوي!",
        },
        features: [
            {
                icon: Sparkles,
                title: {
                    en: 'A Magical Welcome!',
                    ar: 'ترحيب ساحر!',
                },
                description: {
                    en: 'We\'ve revamped the new user tutorial with delightful animations and illustrations to make your first experience even more enjoyable.',
                    ar: 'لقد قمنا بتجديد البرنامج التعليمي للمستخدمين الجدد برسوم متحركة وتوضيحية رائعة لجعل تجربتك الأولى أكثر متعة.',
                },
            },
            {
                icon: Eye,
                title: {
                    en: 'Crystal Clear UI',
                    ar: 'واجهة استخدام أكثر وضوحًا',
                },
                description: {
                    en: 'Text in the "Chef\'s Touch" (remix) modal is now much easier to read. We also fixed a layout issue with the recipe tabs on mobile.',
                    ar: 'أصبح النص في نافذة "أضف لمستك" أسهل في القراءة الآن. أصلحنا أيضًا مشكلة في تخطيط الأزرار على الهواتف.',
                },
            },
            {
                icon: Smartphone,
                title: {
                    en: 'Faster, Better Images on Mobile',
                    ar: 'صور أسرع وأفضل على الهاتف',
                },
                description: {
                    en: 'We\'ve fine-tuned our image generation to deliver faster-loading and more reliable recipe photos, especially for you.',
                    ar: 'لقد قمنا بتحسين عملية إنشاء الصور لتقديم صور وصفات أسرع وأكثر موثوقية، خاصة بالنسبة لك.',
                },
            },
            {
                icon: GlassWater,
                title: {
                    en: 'Safer Sips',
                    ar: 'مشروبات آمنة',
                },
                description: {
                    en: 'Based on your feedback, all suggested drink pairings are now guaranteed to be non-alcoholic and delicious.',
                    ar: 'بناءً على ملاحظاتك، نضمن الآن أن جميع المشروبات المقترحة غير كحولية ولذيذة.',
                },
            },
        ],
    },
];
